apiVersion: v1
kind: Request
metadata:
  id: f22eabd2-6806-4ff6-88d3-e0bea8cef795
  name: Login
  type: GET
spec:
  http:
    method: POST
    url: '{{baseURL}}/auth/v1/login'
    lastUsedEnvironment:
      id: ""
      name: ""
    request:
      headers:
      - id: afa16261-83d8-4897-ae4e-78a92d33c5cc
        key: Content-Type
        value: application/json
        enable: true
      - id: 8d780b27-10f3-48e5-8a6b-978fc50e26b0
        key: Accept
        value: application/json
        enable: true
      pathParams: []
      queryParams: []
      body:
        type: json
        data: |
          {
            "email": "user@test.com",
            "password": "foobar"
          }
      auth:
        type: None
      preRequest:
        type: None
        script: ""
      postRequest:
        type: setEnv
        script: ""
        set:
          target: ""
          statusCode: 0
          from: ""
          fromKey: ""
    responses: []
