apiVersion: v1
kind: Request
metadata:
  id: 1d79c3bd-263d-418c-af45-15afbec1b190
  name: Delete Task
  type: GET
spec:
  http:
    method: DELETE
    url: '{{baseURL}}/todo/v1/tasks/:task_id'
    lastUsedEnvironment:
      id: ""
      name: ""
    request:
      headers:
      - id: 21a684e3-9b84-42ec-a9e0-2e2f5c1d15b4
        key: X-USER-ID
        value: <string>
        enable: true
      - id: 964005f0-ce3e-4949-9f6b-10ea43ebd476
        key: Accept
        value: application/json
        enable: true
      pathParams: []
      queryParams: []
      body:
        type: JSON
        data: ""
      auth:
        type: None
      preRequest:
        type: None
        script: ""
      postRequest:
        type: None
        script: ""
        set:
          target: ""
          from: ""
          fromKey: ""
    responses: []
