apiVersion: v1
kind: Request
metadata:
  id: 973596c0-56c5-426f-9d01-719dfd5f12e1
  name: Get Tasks
  type: GET
spec:
  http:
    method: GET
    url: '{{baseURL}}/todo/v1/tasks?page=1'
    lastUsedEnvironment:
      id: ""
      name: ""
    request:
      headers:
      - id: 96ea31db-e179-4767-b432-1befbeb51855
        key: X-USER-ID
        value: mohsen
        enable: true
      - id: 5a848c04-859f-4d59-b2d7-7b6d999bd6a1
        key: Accept
        value: application/json
        enable: true
      pathParams: []
      queryParams:
      - id: 484d703b-7c2f-480b-8fb6-786ee5259fef
        key: page
        value: "1"
        enable: true
      body:
        type: JSON
        data: ""
      auth:
        type: None
      preRequest:
        type: None
        script: ""
      postRequest:
        type: None
        script: ""
        set:
          target: ""
          from: ""
          fromKey: ""
    responses: []
